format: yamanifest
version: 1.0
---
work/MOM6:
  fullpath: /scratch/x77/cy8964/mom6/setup-mom6-nci-executable/only_mom6_symmetric/MOM6
  hashes:
    binhash: 58ea390293390e59780f2a4deac50aee
    md5: 08f1f4196510d1a1a7cf79b1bcd9ca77
