format: yamanifest
version: 1.0
---
work/INPUT/Ocean0_3D_Claire.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/Ocean0_3D_Claire.nc
  hashes:
    binhash: 73b464b0e6e086b3734747c1766e9437
    md5: a9e43676e2c0acbfe1d48ce856d2ff84
work/INPUT/Ocean1_3D.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/Ocean1_3D.nc
  hashes:
    binhash: c3f094063619b6ecc87e3a61ffa4d951
    md5: 41ff7c7ad45502f2266cc1b21c0fde8c
work/INPUT/atmos_mosaic_tXland_mosaic_t.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/atmos_mosaic_tXland_mosaic_t.nc
  hashes:
    binhash: e8715be7d4e95e427c9c5ff46c811419
    md5: 8b08105be3a15235047140b18cef4c8b
work/INPUT/atmos_mosaic_tXocean_mosaic_t.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/atmos_mosaic_tXocean_mosaic_t.nc
  hashes:
    binhash: c0fe109a57b70004cab14345b55ca0be
    md5: b967da463f9f2ddda6d85953f30e71da
work/INPUT/forcing_prescribed_mr.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/forcing_prescribed_mr.nc
  hashes:
    binhash: c345ef54cdeedf7026985b50a11bbc71
    md5: f71a981fe7a55b11806fd3c8ae52f445
work/INPUT/forcing_prescribed_mr_2.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/forcing_prescribed_mr_2.nc
  hashes:
    binhash: dab61394e1a1b354cec1b7af558408f4
    md5: 49ca5e8d02a7948ff80ffc8919613a32
work/INPUT/grid_spec.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/grid_spec.nc
  hashes:
    binhash: 8e176b5ff8c09e136ffdee30c43beba7
    md5: ce63a487494e67ba5e278fa6f87eedbd
work/INPUT/land_mask.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/land_mask.nc
  hashes:
    binhash: 7c8b2acc0c732c0e725c4f63cf93177e
    md5: b234bbb91c875c27a288e862bac73b15
work/INPUT/land_mosaic_tXocean_mosaic_t.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/land_mosaic_tXocean_mosaic_t.nc
  hashes:
    binhash: 7579195ead26d0cd8306bdf80043bd2e
    md5: bff8af10b9f5fc91b412ae70ea2c884e
work/INPUT/ocean_hgrid.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/ocean_hgrid.nc
  hashes:
    binhash: 999e90e8c2c082127d91a7797e9c68e7
    md5: a848ab6e7d1322baf05462e3182b40c9
work/INPUT/ocean_mask.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/ocean_mask.nc
  hashes:
    binhash: cfe0fd6cf5e389c9b0020a3237351c5d
    md5: 4aae8b75249a148241033c660effd784
work/INPUT/ocean_mosaic.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/ocean_mosaic.nc
  hashes:
    binhash: 4f8774c3a4c3bc2e269f3009f0f0220d
    md5: 2b1a6bfdd0749f99b60f1170d609434a
work/INPUT/topo_masked.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/isomip-prescribedmr/INPUT/topo_masked.nc
  hashes:
    binhash: 7d868769891b73e00dfdc5d11c84c5eb
    md5: ad2f503b3c31a46468b4541fefc41cd5
