format: yamanifest
version: 1.0
---
work/INPUT/Ocean0_3D_Claire.nc:
  fullpath: /g/data/x77/cy8964/idealised-mom6-control/Ocean0_NK36_for_iom3/INPUT/Ocean0_3D_Claire.nc
  hashes:
    binhash: 64c56a0a08732fa246eed19e6c20795a
    md5: a9e43676e2c0acbfe1d48ce856d2ff84
